### ISSUE TITLE
Add option to send all rolls as whispers

### ISSUE THREAD

**Issue by kakaroto** [JacobMcAuley/critical-fumble#1]
As a DM, I don't want my players to see what the roll was, I prefer to tell them (if I decide to use it). So for example, if they do a crit and the roll ends up being "actually, not a crit", I wouldn't want to use it, so I would just not tell them. Same with loot, I'd only let them know what the loot is if they search the body, etc.. Having all the rolls happen as whispers only would be a requirement for me.

**Comment by JacobMcAuley** [comment]
The feature has been added and will be pushed Friday when the new update for FVTT is released!
