### ISSUE TITLE
Remove roll table creation code and use compendium import

### ISSUE THREAD

**Issue by kakaroto** [JacobMcAuley/critical-fumble#2]
You shouldn't need to have the roll tables manually defined in JS code and programmatically generate them. It would make more sense to have them as compendium tables in a pack that the module provides and use the `importFromCompendium` API to import them on first use.

**Comment by JacobMcAuley** [comment]
I didn't realize this was an option when I first started the project.
Thanks for pointing it out. I have updated and will push the release on Friday!
